[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
NearOptimalAlternatives = "a88418a5-8dc5-4f1c-8a3e-d5a75ec49c70"

[compat]
Documenter = "1"
